"""init

Revision ID: 2088f5da2c59
Revises: 
Create Date: 2023-09-12 14:07:23.996910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2088f5da2c59'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    op.create_table('cron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gob'
    )
    op.create_table('entidada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad', sa.String(length=200), nullable=True),
    sa.Column('porcentaje_culminados', sa.Float(), nullable=True),
    sa.Column('porcentaje_avance_fisico', sa.Float(), nullable=True),
    sa.Column('eficiencia', sa.Float(), nullable=True),
    sa.Column('aprobado', sa.Integer(), nullable=True),
    sa.Column('culminados', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gob'
    )
    op.create_table('error_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gob'
    )
    op.create_table('bot_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='gob'
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlativo', sa.String(length=30), nullable=True),
    sa.Column('periodo_fiscal',  sa.String(length=30), nullable=True),
    sa.Column('municipio', sa.String(length=80), nullable=True),
    sa.Column('parroquia', sa.String(length=80), nullable=True),
    sa.Column('entidad', sa.String(length=200), nullable=True),
    sa.Column('tipo_entidad', sa.String(length=80), nullable=True),
    sa.Column('ciclo', sa.String(length=10), nullable=True),
    sa.Column('nombre_proyecto', sa.String(length=600), nullable=True),
    sa.Column('descripcion_proyecto', sa.String(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('monto_proyecto', sa.Float(), nullable=True),
    sa.Column('huso', sa.Float(), nullable=True),
    sa.Column('coord_este', sa.Float(), nullable=True),
    sa.Column('coord_norte', sa.Float(), nullable=True),
    sa.Column('datos_geograficos_validos', sa.Boolean(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('write_date', sa.DateTime(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('avance_fisico_porc', sa.Float(), nullable=True),
    sa.Column('inicio_administrativo', sa.String(length=100), nullable=True),
    sa.Column('entidad_id', sa.String(length=600), nullable=True),
    sa.Column('nombre_institucion', sa.String(length=600), nullable=True),
    sa.Column('monto_gastado', sa.Float(), nullable=True),
    sa.Column('avance_fisico', sa.Float(), nullable=True),
    sa.Column('avance_financiero', sa.Float(), nullable=True),
    sa.Column('id_rsa', sa.String(length=100), nullable=True),
    sa.Column('id_monto', sa.String(length=100), nullable=True),
    sa.Column('rsa', sa.Boolean(), nullable=False),
    sa.Column('rsa_category', sa.String(length=100), nullable=True),
    sa.Column('tipo_ejecucion', sa.String(length=100), nullable=True),
    sa.Column('adjudicacion', sa.String(length=100), nullable=True),
    sa.Column('porcentaje_financiero', sa.Float(), nullable=True),
    sa.Column('estatus_proyecto', sa.String(length=100), nullable=True),
    sa.Column('estatus_rsa', sa.String(length=100), nullable=True),
    sa.Column('estatus_new', sa.String(length=100), nullable=True),
    sa.Column('fecha_inicio_proyecto', sa.String(length=100), nullable=True),
    sa.Column('fecha_culminacion', sa.String(length=100), nullable=True),
    sa.Column('vertice', sa.String(length=600), nullable=True),
    sa.Column('programa', sa.String(length=600), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('category_entidad', sa.String(length=600), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gob'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=5), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='gob'
    )
    op.create_table('user_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['users'], ['gob.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gob'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_update', schema='gob')
    op.drop_table('user', schema='gob')
    op.drop_table('projects', schema='gob')
    op.drop_table('error_report', schema='gob')
    op.drop_table('entidada', schema='gob')
    op.drop_table('cron', schema='gob')
    # ### end Alembic commands ###
