import pandas as pd

datos_entidad = [
    ("ÁREA DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD", "Asociación Civil de Medicina y Ciencias del Deporte (ASOMECID)"),
    ("ÁREA DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD", "Fundación Socialista de Atención Médica Integral del Estado Bolivariano de Guárico (FUSAMIEBG)"),
    ("ÁREA DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD", "Instituto de Ciencia y Tecnología de Estado Bolivariano de Guárico (INCITEBG)"),
    ("ÁREA DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD", "Secretaría de Educación Cultura y Deportes"),
    ("ÁREA DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD", "Secretaría de Educación Universitaria"),
    ("ÁREA DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD", "Secretaría de Salud Pública "),
    ("ÁREA DE CIENCIA, TECNOLOGÍA, EDUCACIÓN Y SALUD", "Sistemas Tecnológicos Alcaraván"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "BusGuarico C.A."),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Construcciones del Estado Bolivariano de Guárico (CONSTRUGUARICO, S.A)"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Construcciones y Vialidad del Estado Bolivariano de Guárico (CONSTRUVIALGUA C.A)"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Distribuidora de Gas del Guárico (DIGASGUA, C.A)  "),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Fundación para la Construcción, Mantenimiento, Conservación y Rehabilitación de las instalaciones e infraestructuras del sistema de salud pública en el estado Bolivariano de Guárico (CONSTRUSALUD)"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Fundación Patria Socialista para la Inversión Social Inmediata del Estado Bolivariano de Guárico (PATRIA SOCIALISTA)"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Hidrológica PÁEZ (HIDROPÁEZ)"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Instituto Autónomo de Vivienda y Habitat del Estado Bolivariano de Guárico (IAVHEBG)"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Ministerio Popular para el Transporte"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Secretaría de Obras Públicas"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Secretaría de Servicios Públicos"),
    ("ÁREA DE OBRAS Y SERVICIOS PÚBLICOS", "Secretaría de Transporte"),
    ("ÁREA DE PROTECCIÓN SOCIAL Y GESTIÓN TERRITORIAL", "FOSIJEG"),
    ("ÁREA DE PROTECCIÓN SOCIAL Y GESTIÓN TERRITORIAL", "Fundación Orquesta Sinfónica del Estado Guárico FOSEG"),
    ("ÁREA DE PROTECCIÓN SOCIAL Y GESTIÓN TERRITORIAL", "Fundación para la Articulación y el Empoderamiento de los Consejos Comunales (EMCOMUNA)"),
    ("ÁREA DE PROTECCIÓN SOCIAL Y GESTIÓN TERRITORIAL", "Fundación Regional  El Niño Simón del Estado de Guárico"),
    ("ÁREA DE PROTECCIÓN SOCIAL Y GESTIÓN TERRITORIAL", "FUNDACULGUA"),
    ("ÁREA DE PROTECCIÓN SOCIAL Y GESTIÓN TERRITORIAL", "IMUGUA"),
    ("ÁREA DE PROTECCIÓN SOCIAL AND GESTIÓN TERRITORIAL", "Instituto de la Juventud del Estado Bolivariano de Guárico (INJUVEBG)"),
    ("ÁREA DE PROTECCIÓN SOCIAL AND GESTIÓN TERRITORIAL", "Instituto Regional de Deportes del Estado Bolivariano de Guárico (IRDEBG) "),
    ("ÁREA DE PROTECCIÓN SOCIAL AND GESTIÓN TERRITORIAL", "MINCOMUNA"),
    ("ÁREA DE PROTECCIÓN SOCIAL AND GESTIÓN TERRITORIAL", "Secretaría de Gestión Político Territorial "),
    ("ÁREA DE PROTECCIÓN SOCIAL AND GESTIÓN TERRITORIAL", "Secretaría de Protección Social"),
    ("ÁREA DE PROTECCIÓN SOCIAL AND GESTIÓN TERRITORIAL", "Somos Venezuela"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Agroguárico Potencia S.A."),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Aguas Termales Hotel y Spa S.A "),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Alimentos del Guárico (Alguarisa S.A)"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Corpoguarico Potencia S.A"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Corporación de Turismo popular del Estado Bolivariano de Guarico (CORPOTURISMO) "),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Fondo de Desarrollo Regional del Estado Guárico (FONDER)"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Fondo de Desarrollo y Emprendimiento del Estado Guárico"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Instituto Público Minero del Estado Bolivariano de Guárico (IPMEBG)"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Secretaría de Alimentación"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Secretaría de Industria y Comercio"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Secretaría de Producción Agropecuaria "),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Sistema Socialista de Proveeduría del  Estado Bolivariano de Guárico (SISOPROGUA)"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Fondo para el Desarrollo Socio Productivo y Nuevos Emprendimientos del Estado Bolivariano de Guárico (FODESOPROEGUA)"),
    ("ÁREA PARA LA PLANIFICACIÓN Y FINANZAS", "Secretaría de Finanzas"),
    ("ÁREA PARA LA PLANIFICACIÓN Y FINANZAS", "Secretaría de Planificación y Presupuesto"),
    ("ÁREA PARA LA SOBERANÍA SEGURIDAD Y PAZ", "Cuerpo de Bomberos del Estado Bolivariano de Guárico"),
    ("ÁREA PARA LA SOBERANÍA SEGURIDAD Y PAZ", "Dirección de Protección Civil y Administración de Desastres"),
    ("ÁREA PARA LA SOBERANÍA SEGURIDAD Y PAZ", "Instituto Autónomo de la Policía del Estado Bolivariano de Guárico. (IAPEBG)"),
    ("ÁREA PARA LA SOBERANÍA SEGURIDAD Y PAZ", "Secretaría de Seguridad y Defensa Ciudadana"),
    ("ÁREA PARA LA SOBERANÍA SEGURIDAD Y PAZ", "Dirección de Protección Civil y Administracion de Desastres"),
    ("ÁREA PARA EL DESARROLLO ECONÓMICO PRODUCTIVO", "Fondo para el  Desarrollo Socio Productivo del Estado Guárico  (FODESOPRO)")
    
]

category_entidad = pd.DataFrame(datos_entidad,columns=['category_entidad','entidad'])  


